# Terraform Azure DevOps pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- task: Terraform@2
  inputs:
    TemplatePath: '/'
    Arguments: 'plan'
    InstallTerraform: true
    UseAzureSub: true
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Visual Studio Enterprise Subscription – MPN(7e6ecd0c-3d73-49d9-b57f-f90f1dc701fb)'
    ManageState: true
    SpecifyStorageAccount: true
    StorageAccountResourceGroup: 'demo-services-rg'
    StorageAccountRM: 'rsterraformdemo'
    StorageContainerName: 'tfstate'