# Terraform Azure DevOps pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.13.3'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Visual Studio Enterprise Subscription – MPN(7e6ecd0c-3d73-49d9-b57f-f90f1dc701fb)'
    backendAzureRmResourceGroupName: 'demo-services-rg'
    backendAzureRmStorageAccountName: 'rsterraformdemo'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'state'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription – MPN(7e6ecd0c-3d73-49d9-b57f-f90f1dc701fb)'
- task: TerraformTaskV1@0
inputs:
  provider: 'azurerm'
  command: 'apply --auto-approve'
  environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription – MPN(7e6ecd0c-3d73-49d9-b57f-f90f1dc701fb)'